version: 2.1

jobs:
  build-and-tests:

    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: UT
          command: mvn test

      - run:
          name: IT
          command: mvn verify

workflows:
  build-and-tests:
    jobs:
      - build-and-tests